apiVersion: v1
kind: ConfigMap 
metadata:
 name: nginx-config
 namespace: md
data:
 default.conf: |
   server {
    listen 80;
    location / {
    root /usr/share/nginx/html;
    index index.html;
    }
     location /api/ {
      resolver 10.96.0.10 ipv6=off;

    proxy_pass http://gateway-service.md.svc.cluster.local:3000;

    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
      }
      }