#common values 
deploymentversion: apps/v1
topologyKey: kubernetes.io/hostname 

#values for harbor registry
harbor:
  SecretHarbor: harbor-cred
  dockerconfigjson: "eyJhdXRocyI6eyIzNC4xMzMuMTEwLjE0MSI6eyJ1c2VybmFtZSI6ImFkbWluIiwicGFzc3dvcmQiOiJIYXJib3JAMTIzNDUiLCJhdXRoIjoiWVdSdGFXNDZTR0Z5WW05eVFERXlNelExIn19fQ=="
  commonRepo: 34.133.110.141/micro-dash

#values for frontend
frontend:
  kind: Deployment 
  name: frontend 
  replicas: 1
  imgname: frontend
  Tag: ci-7
  port: 80
  configMap: nginx-config
  resources:
    requests:
      memory: "64Mi"
      cpu: "50m"
    limits:
      memory: "128Mi"
      cpu: "100m"
  probes:
    liveness:
      path: /
      initialDelaySeconds: 10
      periodSeconds: 10
    readiness:
      path: /
      initialDelaySeconds: 10
      periodSeconds: 10

#values for gateway
gateway:
  kind: Deployment 
  name: gateway 
  replicas: 1
  imgname: gateway 
  Tag: ci-8
  port: 3000
  user_svc_url: http://user-service-svc:3001
  ord_svc_url: http://order-service-svc:3002
  resources:
    requests:
      memory: "128Mi"
      cpu: "100m"
    limits:
      memory: "256Mi"
      cpu: "200m"
  probes:
    liveness:
      path: /health
      port: 3000
      initialDelaySeconds: 20
      periodSeconds: 10
    readiness:
      path: /health
      port: 3000
      initialDelaySeconds: 20
      periodSeconds: 10

#values for order-service and user-service
OrdUsrSer:
  UsrSer: 
    kind: Deployment 
    name: user-service 
    replicas: 1
    imgname: user-service 
    Tag: ci-7
    port: 3001
    svcname: postgres-service
    env:
      db_host: "postgres-service"
      db_port: "5432"
      secretkeyrefname: "db-secret"
      secretkeyrefkeyname: "POSTGRES_USER"
      secretkeyrefkeypass: "POSTGRES_PASSWORD"
      db_name: "usersdb" 
    initconname: wait-for-postgres
    initconimage: busybox
    probes:
      startupProbe:
        httpGet:
          path: /health
          port: 3001
        initialDelaySeconds: 10 
        periodSeconds: 5
        failureThreshold: 3
      livenessProbe: 
        httpGet: 
          path: /health
          port: 3001
        initialDelaySeconds: 10
        periodSeconds: 5
        failureThreshold: 3
      readinessProbe:
        httpGet: 
          path: /health 
          port: 3001 
        initialDelaySeconds: 10
        periodSeconds: 5
        failureThreshold: 3
    resources:
      requests:
        memory: "128Mi"
        cpu: "100m"
      limits:
        memory: "256Mi"
        cpu: "200m"
  OrdSer:
    kind: Deployment 
    name: order-service 
    replicas: 1
    imgname: order-service 
    Tag: ci-7
    port: 3002
    svcname: postgres-service-ord
    env:
      db_host: "postgres-service-ord"
      db_port: "5432"
      secretkeyrefname: "db-secret"
      secretkeyrefkeyname: "POSTGRES_USER"
      secretkeyrefkeypass: "POSTGRES_PASSWORD"
      db_name: "ordersdb"
    initconname: wait-for-postgres
    initconimage: busybox
    probes:
      startupProbe:
        httpGet:
          path: /health
          port: 3002
        initialDelaySeconds: 10 
        periodSeconds: 5
        failureThreshold: 3
      livenessProbe: 
        httpGet: 
          path: /health
          port: 3002
        initialDelaySeconds: 10
        periodSeconds: 5
        failureThreshold: 3
      readinessProbe:
        httpGet: 
          path: /health 
          port: 3002
        initialDelaySeconds: 10
        periodSeconds: 5
        failureThreshold: 3
    resources:
      requests:
        memory: "128Mi"
        cpu: "100m"
      limits:
        memory: "256Mi"
        cpu: "200m"


#values for all services used in this application

services: 
  frontend-service:
    apiVersion: v1 
    kind: Service 
    name: frontend-service
    app: frontend 
    type: ClusterIP
    port: 80
    targetport: 80
    portname: http 
    monitoring: false
  gateway-service:
    apiVersion: v1 
    kind: Service 
    name: gateway-service 
    app: gateway
    type: ClusterIP
    port: 3000
    targetport: 3000
    portname: http 
    monitoring: true
  order-service:
    apiVersion: v1 
    kind: Service 
    name: order-service-svc 
    app: order-service
    type: ClusterIP
    port: 3002
    targetport: 3002
    portname: http 
    monitoring: false
  user-service:
    apiVersion: v1 
    kind: Service 
    name: user-service-svc
    app: user-service
    type: ClusterIP
    port: 3001
    targetport: 3001
    port-name: http 
    monitoring: false
  pg-user-service:
    apiVersion: v1 
    kind: Service 
    name: postgres-service
    app: postgres-user 
    type: ClusterIP
    port: 5432
    targetport: 5432
    portname: http 
    monitoring: false
  pg-order-service:
    apiVersion: v1 
    kind: Service 
    name: postgres-service-ord
    app: postgres-ord 
    type: ClusterIP
    port: 5432
    targetport: 5432
    portname: http 
    monitoring: false


#scaling hpa for 4 services 

hpa: 
  frontend-hpa:
    apiVersion: autoscaling/v2
    kind: HorizontalPodAutoscaler 
    name: frontend-hpa
    appname: frontend
    minreplicas: 1
    maxreplicas: 3
    cpuaverageutilization: 40
    memoryaverageutilization: 70
    scaleupstabsec: 30
    scaleuppodvalue: 2
    scaleupperiodsec: 30
    scaledownstabsec: 120
    scaledownpodvalue: 1
    scaledownperiodsec: 60   
  gateway-hpa:
    apiVersion: autoscaling/v2
    kind: HorizontalPodAutoscaler 
    name: gateway-hpa
    appname: gateway
    minreplicas: 1
    maxreplicas: 5
    cpuaverageutilization: 50
    memoryaverageutilization: 70
    scaleupstabsec: 30
    scaleuppodvalue: 2
    scaleupperiodsec: 30
    scaledownstabsec: 120
    scaledownpodvalue: 1
    scaledownperiodsec: 60
  user-service-hpa:
    apiVersion: autoscaling/v2
    kind: HorizontalPodAutoscaler 
    name: user-service-hpa
    appname: user-service
    minreplicas: 1
    maxreplicas: 5
    cpuaverageutilization: 50
    memoryaverageutilization: 70
    scaleupstabsec: 30
    scaleuppodvalue: 2
    scaleupperiodsec: 30
    scaledownstabsec: 120
    scaledownpodvalue: 1
    scaledownperiodsec: 60
  order-service-hpa: 
    apiVersion: autoscaling/v2
    kind: HorizontalPodAutoscaler 
    name: order-service-hpa
    appname: order-service
    minreplicas: 1
    maxreplicas: 5
    cpuaverageutilization: 50
    memoryaverageutilization: 70
    scaleupstabsec: 30
    scaleuppodvalue: 2
    scaleupperiodsec: 60
    scaledownstabsec: 120
    scaledownpodvalue: 1
    scaledownperiodsec: 60

vpa:
  user-db-vpa:
    apiVersion: autoscaling.k8s.io/v1
    kind: VerticalPodAutoscaler
    name: postgres-user-vpa
    refapiversion: apps/v1
    refkind: Statefulset
    reftargetname: postgres-user
    containername: postgres
    mincpu: 100m
    minmem: 128Mi
    maxcpu: 1000m
    maxmem: 1Gi
    updatemode: Off
  order-db-vpa:
    apiVersion: autoscaling.k8s.io/v1
    kind: VerticalPodAutoscaler
    name: postgres-order-vpa
    refapiversion: apps/v1
    refkind: Statefulset
    reftargetname: postgres-ord
    updatemode: Off
    containername: postgres
    mincpu: 100m
    minmem: 128Mi
    maxcpu: 1000m
    maxmem: 1Gi


st: 
  user-db: 
    apiVersion: apps/v1
    kind: StatefulSet
    name: postgres-user 
    servicename: postgres-service 
    replicas: 1
    app: postgres-user 
    containername: postgres
    containerimage: postgres:15-alpine
    containerport: 5432
    env:
      username:  POSTGRES_USER
      secretkeyrefname: db-secret 
      secretkeyrefkey:  POSTGRES_USER
      passname: POSTGRES_PASSWORD
      secretkeyrefkeypass:  POSTGRES_PASSWORD
      db_name: POSTGRES_DB
      db_value: usersdb 
    volname: postgres-storage
    volmountpath: /var/lib/postgresql/data
    storageclassname: postgres-storage
    storage: 1Gi
    accessmode: ["ReadWriteOnce"]
  order-db: 
    apiVersion: apps/v1
    kind: StatefulSet
    name: postgres-ord
    servicename: postgres-service-ord
    replicas: 1
    app: postgres-ord
    containername: postgres
    containerimage: postgres:15-alpine
    containerport: 5432
    env:
      username:  POSTGRES_USER
      secretkeyrefname: db-secret 
      secretkeyrefkey:  POSTGRES_USER
      passname: POSTGRES_PASSWORD
      secretkeyrefkeypass:  POSTGRES_PASSWORD
      db_name: POSTGRES_DB
      db_value: ordersdb 
    volname: postgres-storage
    volmountpath: /var/lib/postgresql/data
    storageclassname: postgres-storage
    storage: 1Gi
    accessmode: ["ReadWriteOnce"]

storagclass: 
  apiVersion: storage.k8s.io/v1
  kind: StorageClass
  name: postgres-storage 
  provisioner: k8s.io/minikube-hostpath 
  reclaimPolicy: Retain 
  volumeBindingMode: Immediate 
  allowVolumeExpansion: true 


egress:
  frontend-to-gateway: 
    apiVersion: networking.k8s.io/v1
    kind: NetworkPolicy
    name: frontend-to-gateway-egress
    app: frontend 
    targetapp: gateway 
    port: 3000 
    policytype: Egress 
  gateway-to-order-service:
    apiVersion: networking.k8s.io/v1
    kind: NetworkPolicy
    name: gateway-to-user-service-egress
    app: gateway
    targetapp: user-service 
    port: 3001
    policytype: Egress 
  gateway-to-user-service: 
    apiVersion: networking.k8s.io/v1
    kind: NetworkPolicy
    name: gateway-to-order-service-egress
    app: gateway
    targetapp: order-service 
    port: 3002
    policytype: Egress 
  userservice-to-userdb:
    apiVersion: networking.k8s.io/v1
    kind: NetworkPolicy
    name: user-service-to-order-service-egress
    app: user-service 
    targetapp: postgres-user  
    port: 5432
    policytype: Egress 
  orderservice-to-orderdb: 
    apiVersion: networking.k8s.io/v1
    kind: NetworkPolicy
    name: order-service-to-order-service-egress
    app: order-service 
    targetapp: postgres-ord 
    port: 5432
    policytype: Egress 


ingress: 
  frontend-to-gateway: 
    apiVersion: networking.k8s.io/v1
    kind: NetworkPolicy
    name: frontend-to-gateway-ingress
    app: gateway
    targetapp: frontend
    port: 3000
    policytype: Ingress
  gateway-to-user-service:
    apiVersion: networking.k8s.io/v1
    kind: NetworkPolicy
    name: gatway-to-userservice-ingress
    app: user-service
    targetapp: gateway
    port: 3001 
    policytype: Ingress 
  gateway-to-order-service:
    apiVersion: networking.k8s.io/v1
    kind: NetworkPolicy
    name: gatway-to-orderservice-ingress
    app: order-service
    targetapp: gateway
    port: 3002 
    policytype: Ingress 
  user-service-to-userdb:
    apiVersion: networking.k8s.io/v1
    kind: NetworkPolicy
    name: userservice-to-userdb-ingress
    app: postgres-user
    targetapp: user-service
    port: 5432
    policytype: Ingress 
  order-service-to-orderdb: 
    apiVersion: networking.k8s.io/v1
    kind: NetworkPolicy
    name: orderservice-to-orderdb-ingress
    app: postgres-ord
    targetapp: order-service
    port: 5432
    policytype: Ingress 


pdb: 
  frontend: 
    apiVersion: policy/v1
    kind: PodDisruptionBudget 
    name: frontend-pdb
    minavailable: 1 
    app: frontend 
  gateway: 
    apiVersion: policy/v1
    kind: PodDisruptionBudget 
    name: gateway-pdb
    minavailable: 1 
    app: gateway
  user-service: 
    apiVersion: policy/v1
    kind: PodDisruptionBudget 
    name: user-service-pdb
    minavailable: 1 
    app: user-service  
  order-service: 
    apiVersion: policy/v1
    kind: PodDisruptionBudget 
    name: order-service-pdb
    minavailable: 1 
    app: order-service

#ingress configuration 

ingressapp: 
  apiVersion: networking.k8s.io/v1 
  kind: Ingress 
  name: app-ingress
  bodysize: 10m 
  readtimeout: 60 
  sendtimeout: 60 
  limitconnections: 100
  limitrps: 200
  limitrpm: 100
  limitbrustmultiplier: 50
  ingressclassname: nginx 
  defbackendname: def-svc
  defbackendport: 80 
  hostname: micro-dash.local
  secretname: micro-dash-tls
  path: /
  pathtype: Prefix 
  backendservicename: frontend-service 
  port: 80