apiVersion: batch/v1
kind: CronJob 
metadata: 
  name: db-cleanup
  namespace: md 
spec: 
  schedule: "*/1 * * * *"
  jobTemplate:
    spec: 
      template: 
        spec: 
          restartPolicy: OnFailure
          containers: 
            - name: cleanup 
              image: busybox 
              command: ['sh','-c','echo "cleaning old records"']