#sample job to visualize how the job will work
apiVersion: batch/v1
kind: Job 
metadata: 
  name: db-migration
  namespace: md 
spec: 
  ttlSecondsAfterFinished: 120 
  template: 
    spec: 
      restartPolicy: Never
      containers: 
        - name: migration 
          image: postgres:15-alpine
          command: ['sh','-c','echo "running db migrations..."; sleep 3; echo "migration complete"']
          env: 
           - name: POSTGRES_PASSWORD
             valueFrom: 
               secretKeyRef: 
                 name: db-secret
                 key: POSTGRES_PASSWORD