apiVersion: {{ .Values.deploymentversion }}
kind: {{.Values.gateway.kind}}
metadata: 
 name: {{.Release.Name}}-{{.Values.gateway.name}}
 namespace: {{.Release.Namespace}}
spec: 
 replicas: {{.Values.gateway.replicas}}
 selector: 
  matchLabels: 
   app: {{.Values.gateway.name}}
 template:
  metadata:
   labels:
    app: {{.Values.gateway.name}}
  spec: 
  #  affinity:
  #     podAntiAffinity:
  #       requiredDuringSchedulingIgnoredDuringExecution:
  #       - labelSelector:
  #          matchLabels:
  #            app: {{.Values.gateway.name}}
  #         topologyKey: {{.Values.topologyKey}} 
   imagePullSecrets:
     - name: {{.Values.harbor.SecretHarbor}}
   containers: 
    - name: {{.Values.gateway.name}}
      image: {{.Values.harbor.commonRepo}}/{{.Values.gateway.imgname}}:{{.Values.gateway.Tag}}
      ports: 
       - containerPort: {{.Values.gateway.port}}
      env:
        - name: PORT
          value: "{{.Values.gateway.port}}"
        - name: USER_SERVICE_URL
          value: "{{.Values.gateway.user_svc_url}}"
        - name: ORDER_SERVICE_URL
          value: "{{.Values.gateway.ord_svc_url}}"
      {{ with .Values.gateway.resources -}}
      resources:
      {{- toYaml . | nindent 8 -}}
      {{- end }}
      livenessProbe:
          httpGet:
            path: {{ .Values.gateway.probes.liveness.path }}
            port: {{.Values.gateway.port }}
          initialDelaySeconds: {{.Values.gateway.probes.liveness.initialDelaySeconds}}
          periodSeconds: {{.Values.gateway.probes.liveness.periodSeconds}}
      readinessProbe:
          httpGet:
            path: {{ .Values.gateway.probes.readiness.path }}
            port: {{.Values.gateway.port }}
          initialDelaySeconds: {{.Values.gateway.probes.readiness.initialDelaySeconds}}
          periodSeconds: {{.Values.gateway.probes.readiness.periodSeconds}}
