apiVersion: policy/v1
kind: PodDisruptionBudget 
metadata: 
  name: frontend-pdb 
  namespace: md 
spec: 
  minAvailable: 1 #always keep 1 pod atleast 1 pod running 
  #maxUnavailable: 1 allow max 1 pod down at a time 
  selector: 
    matchLabels:
      app: frontend 
--- 
apiVersion: policy/v1
kind: PodDisruptionBudget 
metadata: 
  name: order-service-pdb 
  namespace: md 
spec: 
  minAvailable: 1 #always keep 1 pod atleast 1 pod running 
  #maxUnavailable: 1 allow max 1 pod down at a time 
  selector: 
    matchLabels:
      app: order-service  
--- 
apiVersion: policy/v1
kind: PodDisruptionBudget 
metadata: 
  name: gateway-pdb 
  namespace: md 
spec: 
  minAvailable: 1 #always keep 1 pod atleast 1 pod running 
  #maxUnavailable: 1 allow max 1 pod down at a time 
  selector: 
    matchLabels:
      app: gateway 
--- 
apiVersion: policy/v1
kind: PodDisruptionBudget 
metadata: 
  name: user-service-pdb 
  namespace: md 
spec: 
  minAvailable: 1 #always keep 1 pod atleast 1 pod running 
  #maxUnavailable: 1 allow max 1 pod down at a time 
  selector: 
    matchLabels:
      app: user-service 

