apiVersion: apps/v1
kind: Deployment 
metadata:
 name: order-service
 namespace: md
spec: 
 replicas: 1
 selector: 
  matchLabels: 
   app: order-service 
 template: 
  metadata: 
   labels: 
    app: order-service 
  spec:
   affinity:
      podAntiAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
           matchLabels:
             app: order-service 
          topologyKey: kubernetes.io/hostname  
   initContainers:
     - name: wait-for-postgres
       image: busybox
       command: ['sh','-c','until nc -z postgres-service-ord 5432; do echo "waiting for postgres..."; sleep 2; done; echo "postgres is ready!"']
   imagePullSecrets: 
    - name: harbor-cred
   containers: 
   - name: order-service 
     image: 34.133.110.141/micro-dash/order-service:ci-1
     ports: 
      - containerPort: 3002
     env:
     - name: PORT
       value: "3002"
     - name: DB_HOST
       value: "postgres-service-ord"
     - name: DB_PORT
       value: "5432"
     - name: DB_USER
       valueFrom:
          secretKeyRef:
            name: db-secret
            key: POSTGRES_USER
     - name: DB_PASSWORD
       valueFrom:
          secretKeyRef:
            name: db-secret
            key: POSTGRES_PASSWORD
     - name: DB_NAME
       value: "ordersdb"
     startupProbe:
          httpGet:
            path: /health
            port: 3002
          initialDelaySeconds: 10 
          periodSeconds: 5
          failureThreshold: 2
     livenessProbe: 
          httpGet: 
           path: /health
           port: 3002
          initialDelaySeconds: 10
          periodSeconds: 5
          failureThreshold: 2
     readinessProbe:
         httpGet: 
          path: /health 
          port: 3002 
         initialDelaySeconds: 10
         periodSeconds: 5
         failureThreshold: 2
     resources:
        requests:
          memory: "128Mi"
          cpu: "100m"
        limits:
          memory: "256Mi"
          cpu: "200m"

