apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
spec:
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp
        image: lmacademy/color-api:1.2.0
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
---

apiVersion: v1
kind: Service
metadata: 
  name: color-svc 
spec:
  selector:
    app: myapp 
  ports: 
    - port: 80
      targetPort: 80 
---

apiVersion: v1
kind: Pod
metadata:
  name: curl
  labels:
    app.kubernetes.io/name: curl
spec:
  containers:
  - name: curl
    image: lmacademy/alpine-curl:1.0.0
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
  
