apiVersion: {{.Values.storagclass.apiVersion}}
kind: {{.Values.storagclass.kind}}
metadata: 
  name: {{.Values.storagclass.name}} 
  namespace: {{.Release.Namespace}}
  annotations: 
    storageclass.kubernetes.io/is-default-class: "false"
provisioner: {{.Values.storagclass.provisioner}}
reclaimPolicy: {{.Values.storagclass.reclaimPolicy}}
volumeBindingMode: {{.Values.storagclass.volumeBindingMode}} 
allowVolumeExpansion: {{.Values.storagclass.allowVolumeExpansion}}
