apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata: 
  name: alice-role 
  namespace: md 
roleRef: 
  kind: Role 
  name: alice-role 
  apiGroup: rbac.authorization.k8s.io 
subjects: 
  - kind: User 
    name: alice 
    apiGroup: rbac.authorization.k8s.io
 