apiVersion: {{.Values.ingressapp.apiVersion}}
kind: {{.Values.ingressapp.kind}} 
metadata: 
  name: {{.Release.Name}}-{{.Values.ingressapp.name}}
  namespace: {{.Release.Namespace}}
  annotations: 
    nginx.ingress.kubernetes.io/proxy-body-size: {{.Values.ingressapp.bodysize | quote}}
    nginx.ingress.kubernetes.io/proxy-read-timeout: {{.Values.ingressapp.readtimeout | quote }}
    nginx.ingress.kubernetes.io/proxy-send-timeout: {{.Values.ingressapp.sendtimeout | quote }}
    #limit connection
    nginx.ingress.kubernetes.io/limit-connections: {{.Values.ingressapp.limitconnections | quote }}
    #limit req per sec 
    nginx.ingress.kubernetes.io/limit-rps: {{.Values.ingressapp.limitrps | quote}}
    #limit req per min
    nginx.ingress.kubernetes.io/limits-rpm: {{.Values.ingressapp.limitrpm | quote }}
    #return 429 instead of 503 when limited
    nginx.ingress.kubernetes.io/limit-burst-multiplier: {{.Values.ingressapp.limitbrustmultiplier | quote}}

spec: 
  ingressClassName: {{.Values.ingressapp.ingressclassname}}
  defaultBackend: 
    service: 
      name: {{.Values.ingressapp.defbackendname}} 
      port: 
        number: {{.Values.ingressapp.defbackendport}}
  tls: 
  - hosts:
    -  {{.Values.ingressapp.hostname}}
    secretName: {{.Values.ingressapp.secretname}}
  rules:
  - host: {{.Values.ingressapp.hostname}}
    http:
      paths:
        - path: {{.Values.ingressapp.path}}
          pathType: {{.Values.ingressapp.pathtype}}
          backend:
            service:
              name: {{.Values.ingressapp.backendservicename}}
              port:
                number: {{.Values.ingressapp.port}}